export { photographyAssets } from "virtual:photography-assets";

export const LANGUAGES = ["en", "de"];

export const commonLinks = {
  email: "mailto:nguyenphanmyanh@gmail.com",
  portfolio: "https://www.myanh.de",
  resume: "/assets/phan-my-anh-nguyen-resume-en.pdf",
  resumeEn: "/assets/phan-my-anh-nguyen-resume-en.pdf",
  resumeDe: "/assets/phan-my-anh-nguyen-lebenslauf-de.pdf",
};

const boehringerSamples = [
  {
    image: "/boehringer-samples/mso-announcement.jpeg",
    alt: "Boehringer Ingelheim MSO announcement template",
    title: "MSO Announcement",
    meta: "Quality systems communication template",
  },
  {
    image: "/boehringer-samples/mso-newsletter.jpeg",
    alt: "Boehringer Ingelheim MSO newsletter layout",
    title: "MSO Newsletter",
    meta: "Newsletter concept for quality-system updates",
  },
  {
    image: "/boehringer-samples/qms-portal.png",
    alt: "Boehringer Ingelheim QMS portal landing page",
    title: "QMS Portal",
    meta: "Central portal concept for MSO resources",
  },
  {
    image: "/boehringer-samples/mso-quiz.png",
    alt: "Boehringer Ingelheim MSO quiz screen",
    title: "MSO Quiz Screen",
    meta: "Interactive awareness concept for the MSO network",
  },
];

const enProjects = [
  {
    image: "/boehringer.png",
    alt: "Boehringer Ingelheim QMS portal project visual",
    eyebrow: "Boehringer Ingelheim · UX/UI Design Intern",
    title: "Restructuring a QMS portal for clearer quality management.",
    body: "Analyzed and reorganized QMS intranet pages, then shaped a more user-friendly portal concept for quality-management content and internal access.",
    cta: "View work",
    href: "#contact",
    sampleGalleryTitle: "Boehringer work samples",
    samples: boehringerSamples,
    side: "left",
  },
  {
    image: "/volkswagen.png",
    alt: "Volkswagen Entgelt-Wiki internal platform project visual",
    eyebrow: "Volkswagen AG · Internal Communication Platform",
    title: "Designing Entgelt-Wiki for internal communication.",
    body: "Supported an internal compensation-wiki rollout through usage analysis, a survey with around 100 participants, documentation, publishing, and intranet design implementation.",
    cta: "View work",
    href: "/assets/vw-platform.pdf",
    side: "right",
  },
  {
    image: "/encoway.png",
    alt: "encoway UX/UI working student project visual",
    eyebrow: "encoway GmbH · Working Student UX/UI",
    title: "Turning UX research into wireframes, prototypes, and team materials.",
    body: "Worked across competitor analysis, expert reviews, wireframes, prototypes, UX/UI communication materials, and the UX/UI team SharePoint presence.",
    cta: "Discuss this work",
    href: "#contact",
    side: "left",
  },
];

const deProjects = [
  {
    image: "/boehringer.png",
    alt: "Boehringer Ingelheim QMS-Portal Projektvisual",
    eyebrow: "Boehringer Ingelheim · UX/UI Design Praktikantin",
    title: "Ein QMS-Portal klarer und nutzerfreundlicher strukturieren.",
    body: "Analyse und Neustrukturierung von QMS-Intranetseiten sowie Gestaltung eines nutzerfreundlicheren Portalkonzepts für Qualitätsmanagement-Inhalte.",
    cta: "Arbeit ansehen",
    href: "#contact",
    sampleGalleryTitle: "Boehringer Arbeitsproben",
    samples: boehringerSamples,
    side: "left",
  },
  {
    image: "/volkswagen.png",
    alt: "Volkswagen Entgelt-Wiki Projektvisual",
    eyebrow: "Volkswagen AG · Interne Kommunikationsplattform",
    title: "Entgelt-Wiki als interne Kommunikationsplattform gestalten.",
    body: "Unterstützung des Rollouts durch Nutzungsanalyse, eine Umfrage mit rund 100 Teilnehmenden, Dokumentation, Publishing und Umsetzung im VW-Intranet.",
    cta: "Arbeit ansehen",
    href: "/assets/vw-platform.pdf",
    side: "right",
  },
  {
    image: "/encoway.png",
    alt: "encoway UX/UI Werkstudentin Projektvisual",
    eyebrow: "encoway GmbH · Werkstudentin UX/UI Design",
    title: "Von UX-Analyse zu Wireframes, Prototypen und Team-Materialien.",
    body: "Arbeit an Wettbewerbsanalysen, Expert Reviews, Wireframes, Prototypen, UX/UI-Kommunikationsmaterialien und der SharePoint-Seite des UX/UI-Teams.",
    cta: "Projekt besprechen",
    href: "#contact",
    side: "left",
  },
];

export const content = {
  en: {
    languageLabel: "Language",
    nav: {
      top: "Home",
      work: "Work",
      playground: "Play",
      contact: "Contact",
    },
    cursor: "Explore",
    splash: ["Research", "Wireframes", "Prototypes", "SharePoint", "Intranet UX", "Figma"],
    hero: {
      greeting: "Hi, I’m",
      name: "My Anh.",
      image: "/hero.png",
      imageAlt: "Portrait of Phan My Anh Nguyen",
      bio: [
        { text: "UX/UI Designer " },
        { text: "with a Media Informatics background", strong: true },
        { text: ", shaping clear digital experiences through user research, prototyping, intranet/SharePoint work, and design-system thinking." },
      ],
      scroll: "Scroll to work",
      workCta: "View work",
    },
    ticker: ["UX/UI Design", "User Research", "Wireframing", "Prototyping", "SharePoint", "Intranet UX", "Design Systems", "HTML/CSS"],
    work: {
      eyebrow: "Selected experience",
      title: "Design work across intranets, platforms, and practical UX systems.",
      subtitle: "",
      projects: enProjects,
    },
    playground: {
      title: "Playground",
      subtitle: "A softer corner for the creative habits that feed my design work.",
      cards: [
        {
          title: "Content Creation",
          text: "Filming, editing, and social-media storytelling.",
          image: "/content-creation-thumbnail.png",
          alt: "Creative content thumbnail",
          href: "#contact",
          className: "card-minerva",
        },
        {
          title: "Video Editing",
          text: "Short-form motion, cuts, rhythm, and visual flow.",
          image: "/video-editing-thumbnail.png",
          alt: "Filming and video editing thumbnail",
          href: "#contact",
          className: "card-bloom",
        },
        {
          title: "Photography",
          text: "Moments I frame outside the interface.",
          image: "/photo-book-thumbnail.png",
          alt: "Ocean photo book thumbnail",
          href: "/photography",
          className: "card-photo",
        },
      ],
    },
    testimonials: {
      eyebrow: "What people say",
      title: "References from previous employers.",
      subtitle: "Reference and certificate pages from Volkswagen Group, KUKA, and encoway. Tap a document to view it larger.",
      cards: [
        {
          name: "Volkswagen Group",
          role: "Volkswagen Group Reference Letter",
          image: "/references/large/volkswagen-reference-en.png",
          thumbnail: "/references/thumbs/volkswagen-reference-en.png",
          alt: "Volkswagen Group English reference letter for Phan My Anh Nguyen",
        },
        {
          name: "Volkswagen Group",
          role: "Volkswagen Group Reference Letter",
          image: "/references/large/volkswagen-zeugnis-de.png",
          thumbnail: "/references/thumbs/volkswagen-zeugnis-de.png",
          alt: "Volkswagen Group German internship certificate for Phan My Anh Nguyen",
        },
        {
          name: "KUKA",
          role: "KUKA Reference Letter",
          image: "/references/large/kuka-praktikum-1.png",
          thumbnail: "/references/thumbs/kuka-praktikum-1.png",
          alt: "KUKA internship certificate page 1 for Phan My Anh Nguyen",
        },
        {
          name: "KUKA",
          role: "KUKA Reference Letter",
          image: "/references/large/kuka-praktikum-2.png",
          thumbnail: "/references/thumbs/kuka-praktikum-2.png",
          alt: "KUKA performance assessment page 2 for Phan My Anh Nguyen",
        },
        {
          name: "KUKA",
          role: "KUKA Reference Letter",
          image: "/references/large/kuka-praktikum-3.png",
          thumbnail: "/references/thumbs/kuka-praktikum-3.png",
          alt: "KUKA internship certificate cover letter page 3 for Phan My Anh Nguyen",
        },
        {
          name: "encoway",
          role: "encoway Reference Letter",
          image: "/references/large/encoway-letter.png",
          thumbnail: "/references/thumbs/encoway-letter.png",
          alt: "encoway cover letter for Phan My Anh Nguyen",
        },
        {
          name: "encoway",
          role: "encoway Reference Letter",
          image: "/references/large/encoway-zeugnis.png",
          thumbnail: "/references/thumbs/encoway-zeugnis.png",
          alt: "encoway employment certificate for Phan My Anh Nguyen",
        },
      ],
    },
    footer: {
      eyebrow: "Let’s connect",
      headline: "Have a UX/UI role, project, or portfolio note in mind?",
      cta: "Email My Anh",
      copyright: "© 2026 Phan My Anh Nguyen",
      tagline: "Frankfurt am Main · UX/UI Designer",
      links: [
        { label: "Portfolio", href: commonLinks.portfolio },
        { label: "Email", href: commonLinks.email },
        { label: "Resume", href: commonLinks.resumeEn },
      ],
    },
    photography: {
      title: "Photography",
      subtitle: "Visual notes, moving moments, and small experiments from outside the interface.",
      empty: "New experience will be coming soon! >.<",
    },
  },
  de: {
    languageLabel: "Sprache",
    nav: {
      top: "Start",
      work: "Arbeit",
      playground: "Play",
      contact: "Kontakt",
    },
    cursor: "Ansehen",
    splash: ["Research", "Wireframes", "Prototypen", "SharePoint", "Intranet UX", "Figma"],
    hero: {
      greeting: "Hi, ich bin",
      name: "My Anh.",
      image: "/hero.png",
      imageAlt: "Porträt von Phan My Anh Nguyen",
      bio: [
        { text: "UX/UI Designerin " },
        { text: "mit Medieninformatik-Hintergrund", strong: true },
        { text: " und Erfahrung in User Research, Prototyping, SharePoint/Intranet-Konzepten und Design-System-orientierter Gestaltung." },
      ],
      scroll: "Zur Arbeit scrollen",
      workCta: "Arbeiten ansehen",
    },
    ticker: ["UX/UI Design", "User Research", "Wireframing", "Prototyping", "SharePoint", "Intranet UX", "Design Systems", "HTML/CSS"],
    work: {
      eyebrow: "Ausgewählte Erfahrung",
      title: "Designarbeit für Intranets, Plattformen und praktische UX-Systeme.",
      subtitle: "",
      projects: deProjects,
    },
    playground: {
      title: "Playground",
      subtitle: "Ein weicherer Ort für kreative Interessen, die meine Designarbeit mitprägen.",
      cards: [
        {
          title: "Content Creation",
          text: "Filmen, Schneiden und Storytelling für Social Media.",
          image: "/content-creation-thumbnail.png",
          alt: "Creative Content Thumbnail",
          href: "#contact",
          className: "card-minerva",
        },
        {
          title: "Video Editing",
          text: "Kurzvideos, Schnitte, Rhythmus und visueller Flow.",
          image: "/video-editing-thumbnail.png",
          alt: "Filming und Video Editing Thumbnail",
          href: "#contact",
          className: "card-bloom",
        },
        {
          title: "Fotografie",
          text: "Momente, die ich außerhalb des Interfaces rahme.",
          image: "/photo-book-thumbnail.png",
          alt: "Ocean Photo Book Thumbnail",
          href: "/photography",
          className: "card-photo",
        },
      ],
    },
    testimonials: {
      eyebrow: "Was andere sagen",
      title: "Referenzen früherer Arbeitgeber.",
      subtitle: "Referenz- und Zeugnisseiten von Volkswagen Group, KUKA und encoway. Tippe ein Dokument an, um es größer zu sehen.",
      cards: [
        {
          name: "Volkswagen Group",
          role: "Volkswagen Group Reference Letter",
          image: "/references/large/volkswagen-reference-en.png",
          thumbnail: "/references/thumbs/volkswagen-reference-en.png",
          alt: "Englische Volkswagen Group Reference für Phan My Anh Nguyen",
        },
        {
          name: "Volkswagen Group",
          role: "Volkswagen Group Reference Letter",
          image: "/references/large/volkswagen-zeugnis-de.png",
          thumbnail: "/references/thumbs/volkswagen-zeugnis-de.png",
          alt: "Deutsches Volkswagen Group Zeugnis für Phan My Anh Nguyen",
        },
        {
          name: "KUKA",
          role: "KUKA Reference Letter",
          image: "/references/large/kuka-praktikum-1.png",
          thumbnail: "/references/thumbs/kuka-praktikum-1.png",
          alt: "KUKA Praktikumszeugnis Seite 1 für Phan My Anh Nguyen",
        },
        {
          name: "KUKA",
          role: "KUKA Reference Letter",
          image: "/references/large/kuka-praktikum-2.png",
          thumbnail: "/references/thumbs/kuka-praktikum-2.png",
          alt: "KUKA Leistungsbeurteilung Seite 2 für Phan My Anh Nguyen",
        },
        {
          name: "KUKA",
          role: "KUKA Reference Letter",
          image: "/references/large/kuka-praktikum-3.png",
          thumbnail: "/references/thumbs/kuka-praktikum-3.png",
          alt: "KUKA Anschreiben Seite 3 für Phan My Anh Nguyen",
        },
        {
          name: "encoway",
          role: "encoway Reference Letter",
          image: "/references/large/encoway-letter.png",
          thumbnail: "/references/thumbs/encoway-letter.png",
          alt: "encoway Anschreiben für Phan My Anh Nguyen",
        },
        {
          name: "encoway",
          role: "encoway Reference Letter",
          image: "/references/large/encoway-zeugnis.png",
          thumbnail: "/references/thumbs/encoway-zeugnis.png",
          alt: "encoway Arbeitszeugnis für Phan My Anh Nguyen",
        },
      ],
    },
    footer: {
      eyebrow: "Lass uns sprechen",
      headline: "Geht es um eine UX/UI-Rolle, ein Projekt oder Feedback zum Portfolio?",
      cta: "My Anh mailen",
      copyright: "© 2026 Phan My Anh Nguyen",
      tagline: "Frankfurt am Main · UX/UI Designerin",
      links: [
        { label: "Portfolio", href: commonLinks.portfolio },
        { label: "E-Mail", href: commonLinks.email },
        { label: "Lebenslauf", href: commonLinks.resumeDe },
      ],
    },
    photography: {
      title: "Fotografie",
      subtitle: "Visuelle Notizen, bewegte Momente und kleine Experimente außerhalb des Interfaces.",
      empty: "New experience will be coming soon! >.<",
    },
  },
};
